config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :books, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only:[:new, :create, :index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

# Bookモデルのカラムのバリデーションは以下の通りにし、有効でない場合はバリデーションエラーを返してください。
# title：空でないように設定してください。
# body：空でない、かつ最大200文字までに設定してください。

  validates:title, presence:true
  validates:body, presence:true, length:{maximum:200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

# Userモデルのカラムのバリデーションは以下の通りにし、有効でない場合はバリデーションエラーを返してください。
# name：一意性を持たせ、かつ2～20文字の範囲で設定してください。
# introduction：最大50文字までに設定してください。
  validates:name, presence:true, length:{minimum:2,maximum:20}, uniqueness:true
  validates:introduction, length:{maximum:50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except:[:top,:about]
  before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_current_user,{only:[:edit,:update, :destroy]}

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      flash[:notice] = "error"
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user = current_user
       render :edit
    else
       redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "successfully."
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "error."
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
       flash[:notice]="Book was successfully destroyed."
       redirect_to books_path
    end
  end

 private

  def ensure_current_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
  
  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :ensure_current_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
      if @user.update(user_params)
        flash[:notice] = "successfully."
        redirect_to user_path(@user.id)
      else
        flash[:notice] = "error."
        render 'edit'
      end
  end

  private

  def ensure_current_user
      @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if @book.errors.any? %>
<h3>
  <%= @book.errors.count %>errors prohibited this obj from being saved:</h3></br>
  <% @book.errors.full_messages.each do |message| %>
   
    <ul>
        <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/books/_submit.html.erb
    <h2 class="mt-3">New book</h2>

      <%= form_with model:book, local:true do |f| %>
       <div class="form-group">
        <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title" %>
       </div>
       <div class="form-group">
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class:"form-control book_body" %>
       </div>
       <div class="form-group">
          <%= f.submit "Create Book", class:"btn btn-success" %>
       </div>
      <% end %>

app/views/books/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book, local:true do |f| %>

      <div class="form-group">
        <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title" %>
      </div>
      <div class="form-group">
          <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-success" %>
      </div>
      <% end %>

      <div class="menu">
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "books/error" %>
      <%= render "users/userinfo", user:@user %>
      <%= render "books/submit", book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill,60,60, fallback:"no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/userinfo", user:@user %>
      <%= render "books/submit", book:@book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill,40,40, format:"jpeg", fallback:"no_image.jpg" %>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if @user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class:"btn btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @user == current_user %>
                <%= link_to "Destroy", book_path(@book), method: :delete, 'data-confirm' => "本当に削除しますか？" , class:"btn btn-danger" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
   </div>
</div>

app/views/homes/about.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-lg-5 mx-auto">
    <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <%= link_to "Log in",new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %></br>
              <%= link_to "Sign up",new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
            </div>
          </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Bookers2</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Bookers", root_path, class:"navbar-brand"  %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if user_signed_in? %>
          <!--ログイン済み？-->
      　　<!--true-->
            <ul class="navbar-nav  ml-auto">
              <li class="nav-item">
                <%= link_to user_path(current_user),class:"nav-link text-white fas fa-home pr-1" do %>Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path,class:"nav-link text-white fas fa-users pr-1" do %>Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path,class:"nav-link text-white fas fa-book-open pr-1" do %>Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path,method: :delete,class:"nav-link text-white fas fa-sign-out-alt pr-1" do %>Log out
                <% end %>
              </li>
            </ul>
          <% else %>
        <!--false-->
          <!--<div class="collapse navbar-collapse" id="navbarNavDropdown">-->
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to root_path,class:"nav-link text-light fas fa-home" do %>Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to home_about_path,class:"nav-link text-light fas fa-link" do %>About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path,class:"nav-link text-light fas fa-user-plus" do %>Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path,class:"nav-link text-light fas fa-sign-in-alt" do %>Log in
                <% end %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
  </header>
    <span class="text-success">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class:"#{key}") %>
        <% end %>
    </span>
 <main>
  <%= yield %>
 </main>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_error.html.erb
<% if @book.errors.any? %>
<h3>
  <%= @book.errors.count %>errors prohibited this obj from being saved:</h3></br>
  <% @book.errors.full_messages.each do |message| %>
   
    <ul>
        <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill,63,63, format: "jpeg", fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
      </tbody>
    </table>
  <div class="row">
    <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
    <% end %>
  </div>

app/views/users/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <span class="text-danger">
      <% if @user.errors.any? %>
      <h3>
        <%= @user.errors.count %>errors prohibited this obj from being saved:</h3></br>
        <% @user.errors.full_messages.each do |message| %>
          <ul>
              <li><%= message %></li>
          </ul>
        <% end %>
      <% end %>
      </span>

        <%= form_with model:@user, local:true do |f| %>

         <div class="form-group">
          <div class="field_with_errors">
            <label for="user_name">Name</label>
          </div>
           <%= f.text_field:name, id:"user_name", class:"form-control name" %>
         </div>

         <div class="form-group">
           <label for="user_image">Image</label>
           <%= f.attachment_field :profile_image, class:"form-control_file user_image" %>
           </div>

         <div class="form-group">
           <label for="user_introduction">Introduction</label>
           <%= f.text_field:introduction, id:"user_introduction", class:"form-control introduction" %>
         </div>

         <div class="form-group">
            <%= f.submit "Update User", class:"btn btn-secondary" %>
         </div>

        <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3" >
      <%= render "books/error" %>
      <%= render "users/userinfo", user:@user %>
      <%= render "books/submit", book:@book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-resposive">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill,60,60, fallback:"no_image.jpg" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/userinfo", user:@user %>
      <%= render "books/submit", book:@book %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path do %>
                <%= attachment_image_tag @user, :profile_image, :fill,40,40, fallback: "no_image.jpeg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
  </div>
  </div>
</div>